export const queryKeys = {
  categories: ['categories'] as const,
  category: (id: string) => ['categories', id] as const,
  products: (filters?: Record<string, string | undefined>) => ['products', filters ?? {}] as const,
  product: (id: string) => ['products', id] as const,
  productBySlug: (slug: string) => ['products', 'slug', slug] as const,
  orders: (filters?: Record<string, string | number | undefined>) => ['orders', filters ?? {}] as const,
  order: (id: string) => ['orders', id] as const,
  orderRefunds: (orderId: string) => ['orders', orderId, 'refunds'] as const,
  orderReceipt: (orderId: string) => ['orders', orderId, 'receipt'] as const,
  cart: (id: string) => ['cart', id] as const,
  users: ['users'] as const,
  user: (id: string) => ['users', id] as const,
  suppliers: ['suppliers'] as const,
  supplier: (id: string) => ['suppliers', id] as const,
  inventory: ['inventory'] as const,
  inventoryItem: (id: string) => ['inventory', id] as const,
  me: ['auth', 'me'] as const,
  returns: (filters?: Record<string, string | number | undefined>) => ['returns', filters ?? {}] as const,
  return: (id: string) => ['returns', id] as const,
  storeCredit: ['returns', 'store-credit'] as const,
  conversations: (filters?: Record<string, string | undefined>) => ['conversations', filters ?? {}] as const,
  conversation: (id: string) => ['conversations', id] as const,
  messages: (conversationId: string) => ['conversations', conversationId, 'messages'] as const,
  quickReplies: ['whatsapp', 'quick-replies'] as const,
  invoices: (filters?: Record<string, string | number | undefined>) => ['invoices', filters ?? {}] as const,
  invoice: (id: string) => ['invoices', id] as const,
  creditNotes: (filters?: Record<string, string | number | undefined>) => ['credit-notes', filters ?? {}] as const,
  creditNote: (id: string) => ['credit-notes', id] as const,
  financeIncomes: (filters?: Record<string, string | number | undefined>) =>
    ['finance', 'incomes', filters ?? {}] as const,
  financeIncome: (id: string) => ['finance', 'incomes', id] as const,
  financeExpenseCategories: ['finance', 'expense-categories'] as const,
  financeExpenses: (filters?: Record<string, string | number | undefined>) =>
    ['finance', 'expenses', filters ?? {}] as const,
  financeCashFlow: (from: string, to: string) => ['finance', 'cash-flow', from, to] as const,
  financeStoreCredits: ['finance', 'store-credits'] as const,
  notificationPreferences: ['notifications', 'preferences'] as const,
  search: (query: string) => ['search', query] as const,
  catalog: (filters?: Record<string, string | number | boolean | undefined>) =>
    ['catalog', filters ?? {}] as const,
  chatMessages: (sessionId: string) => ['chat', sessionId, 'messages'] as const,
  productContentDraft: (productId: string) => ['ai', 'products', productId, 'draft'] as const,
  faqs: ['ai', 'faqs'] as const,
  adminFaqs: ['ai', 'faqs', 'admin'] as const,
  adminCmsPages: ['ai', 'cms-pages', 'admin'] as const,
  cmsPageBySlug: (slug: string) => ['ai', 'cms-page', slug] as const,
  marketingPromotions: ['marketing', 'promotions'] as const,
  analyticsOverview: (days: number) => ['analytics', 'overview', days] as const,
  analyticsFunnel: (days: number) => ['analytics', 'funnel', days] as const,
  analyticsCohorts: (weeks: number) => ['analytics', 'cohorts', weeks] as const,
  productReviews: (productId: string) => ['reviews', productId] as const,
  productReviewSummary: (productId: string) => ['reviews', productId, 'summary'] as const,
  pendingReviews: ['reviews', 'pending'] as const,
  loyaltyAccount: ['loyalty', 'me'] as const,
  loyaltyTransactions: ['loyalty', 'transactions'] as const,
  referralCode: ['referrals', 'code'] as const,
  referralPerformance: (scope: 'me' | 'admin') => ['referrals', 'performance', scope] as const,
  companies: ['b2b', 'companies'] as const,
  myCompany: ['b2b', 'me', 'company'] as const,
  companyPrices: (companyId: string) => ['b2b', 'companies', companyId, 'prices'] as const,
  quotes: (scope: 'me' | 'admin', status?: string) => ['quotes', scope, status ?? 'all'] as const,
  quotesRoot: ['quotes'] as const,
  quote: (id: string) => ['quotes', id] as const,
  ordersRoot: ['orders'] as const,
  marketplaceChannels: ['marketplace', 'channels'] as const,
  marketplaceListings: (channel?: string) => ['marketplace', 'listings', channel ?? 'all'] as const,
  marketplaceListingsRoot: ['marketplace', 'listings'] as const,
  accountingProviders: ['accounting', 'providers'] as const,
  accountingSyncRecords: ['accounting', 'sync-records'] as const,
  marketplaceFeeReconciliations: ['accounting', 'marketplace-fees'] as const,
  privacyExport: ['privacy', 'export'] as const,
  subscriptionPlans: ['subscriptions', 'plans'] as const,
  mySubscriptions: ['subscriptions', 'me'] as const,
  subscriptionsRoot: ['subscriptions'] as const,
  loyaltyRedemptionQuote: (subtotal: number, points?: number) =>
    ['loyalty', 'quote', subtotal, points] as const,
};

